name: Build
on:
  schedule:
    - cron: "7 6 * * 0" # Weekly on Sundays at 15:07 (JST)
  push:
    branches:
      - master
    paths:
      - "Dockerfile"
      - ".github/workflows/**"

env:
  DOCKER_USERNAME: tiryoh
  DOCKER_IMAGENAME: docker-ubuntu-sweb

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            { version: 20.04, code: focal, latest: false },
            { version: 22.04, code: jammy, latest: true },
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Current Date
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGENAME }}
          tags: |
            type=raw,value=${{ matrix.os.code }}
            type=raw,value=${{ matrix.os.code }}-{{date 'YYYYMMDDTHHmm'}}
          flavor: |
            latest=${{ matrix.os.latest }}
            prefix=
            suffix=

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          build-args: BASE_TAG=${{ matrix.os.code }}
          context: .
          platforms: linux/amd64, linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}
          cache-from: type=gha,scope=${{ matrix.os.code }}
          cache-to: type=gha,mode=max,scope=${{ matrix.os.code }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
